name: scribblr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nb_utils: ^7.1.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  country_picker: ^2.0.27
  ionicons: ^0.2.2
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.15
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - images/scribblr/
  - images/scribblr/authors/
  - images/scribblr/articles/
  - images/scribblr/icons/
  - images/scribblr/lottie/
  - images/scribblr/walkthrough/